---
- name: Manage DNS with IasC
  hosts: all
  become: yes

  tasks:
    - name: Create /etc/hosts file from template
      template:
        src: hosts.j2
        dest: /etc/hosts
      notify:
        - Restart networking

    - name: Create resolv.conf file from template
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf

  handlers:
    - name: Restart some service
      debug:
        msg: "You can use handlers to restart some service for changes to take affect.  It will only restart the service if a change is made"
