---
- name: Manage DNS with IasC
  hosts: all
  become: yes
  vars:
    destination_dir: /opt/scripts
    zip_file: scripts.zip

  tasks:
    - name: Create /etc/hosts file from template
      template:
        src: hosts.j2
        dest: /etc/hosts
      notify:
        - Restart networking

    - name: Create resolv.conf file from template
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf

    - name: Ensure destination directory exists
      file:
        path: "{{ destination_dir }}"
        state: directory
        mode: '0755'

    - name: Copy scripts.zip to the target host
      copy:
        src: "files/{{ zip_file }}"
        dest: "{{ destination_dir }}/{{ zip_file }}"

    - name: Ensure unzip is installed
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - unzip
        - python3

    - name: Unzip scripts.zip in the destination directory
      ansible.builtin.unarchive:
        src: "{{ destination_dir }}/{{ zip_file }}"
        dest: "{{ destination_dir }}"
        remote_src: yes

#    - name: Set execute permissions on all files in the directory
#      file:
#        path: "{{ item.path }}"
#        state: file
#        mode: '0755'
#      with_fileglob:
#        - "{{ destination_dir }}/*"

    - name: Find all files in the destination directory
      find:
        paths: "{{ destination_dir }}"
        recurse: no
      register: found_files

    - name: Set execute permissions on all files
      file:
        path: "{{ item.path }}"
        state: file
        mode: '0755'
      loop: "{{ found_files.files }}"

    - name: Ensure the directory itself has correct permissions
      file:
        path: "{{ destination_dir }}"
        state: directory
        mode: '0755'

    - name: Execute each Python script
      shell: "python3 {{ item.path }}"
      loop: "{{ found_files.files }}"

  handlers:
    - name: Restart some service
      debug:
        msg: "You can use handlers to restart some service for changes to take affect.  It will only restart the service if a change is made"
