---
- name: Manage DNS with IasC
  hosts: all
  become: yes

  tasks:
    - name: Create /etc/hosts file from template
      template:
        src: templates/etc_hosts.j2
        dest: /etc/hosts
      notify:
        - Restart networking

    - name: Create /etc/resolv.conf file from template
      template:
        src: templates/resolv_conf.j2
        dest: /etc/resolv.conf

  handlers:
    - name: Restart networking
      service:
        name: network
        state: restarted
